#!/usr/bin/env bash
set -euo pipefail

ENVIRONMENT="${1:-staging}"
PROJECT_ID="${PROJECT_ID:-business-heroes-infinity}"
REGION="${REGION:-asia-southeast1}"
SKIP_DEPLOY_PREFLIGHT="${SKIP_DEPLOY_PREFLIGHT:-false}"
SERVICE="vidsloom-${ENVIRONMENT}"
SERVICE_ACCOUNT="vidsloom-runner@${PROJECT_ID}.iam.gserviceaccount.com"
CLOUD_RUN_TIMEOUT_SECONDS="${CLOUD_RUN_TIMEOUT_SECONDS:-3600}"
if [[ "${ENVIRONMENT}" == "production" ]]; then
  PUBLIC_BASE_URL="${PUBLIC_BASE_URL:-https://vidsloom.com}"
else
  PUBLIC_BASE_URL="${PUBLIC_BASE_URL:-https://staging.vidsloom.com}"
fi
SENDGRID_SECRET_NAME="${SENDGRID_SECRET_NAME:-vidsloom_sendgrid_api_key}"
SENDGRID_FROM_EMAIL="${SENDGRID_FROM_EMAIL:-noreply@learnadaptresearch.org}"
SENDGRID_FROM_NAME="${SENDGRID_FROM_NAME:-VIDSLOOM}"
SENDGRID_REPLY_TO_EMAIL="${SENDGRID_REPLY_TO_EMAIL:-support@learnadaptresearch.org}"
VIDSLOOM_SALES_EMAIL="${VIDSLOOM_SALES_EMAIL:-admin@learnadaptresearch.org}"
SENDGRID_CONTACTDB_LIST_IDS="${SENDGRID_CONTACTDB_LIST_IDS:-31152278}"
VIDSLOOM_WHATSAPP_NUMBER="${VIDSLOOM_WHATSAPP_NUMBER:-6592978409}"
VIDSLOOM_SMS_NUMBER="${VIDSLOOM_SMS_NUMBER:-6592978409}"
VIDSLOOM_QA_USERNAME="${VIDSLOOM_QA_USERNAME:-vidsloom_qa_20260614012838}"
VIDSLOOM_GENERATED_ASSET_BUCKET="${VIDSLOOM_GENERATED_ASSET_BUCKET:-vidsloom-generated-assets-business-heroes-infinity}"
VIDSLOOM_QA_PASSWORD_SECRET_NAME="${VIDSLOOM_QA_PASSWORD_SECRET_NAME:-vidsloom_qa_password}"
VIDSLOOM_AUTH_SECRET_NAME="${VIDSLOOM_AUTH_SECRET_NAME:-vidsloom_auth_secret}"
VIDSLOOM_AUTOMATION_SECRET_NAME="${VIDSLOOM_AUTOMATION_SECRET_NAME:-vidsloom_automation_secret}"
VIDSLOOM_PLANNING_QUEUE="${VIDSLOOM_PLANNING_QUEUE:-vidsloom-planning-${ENVIRONMENT}}"
VIDSLOOM_PLANNING_QUEUE_LOCATION="${VIDSLOOM_PLANNING_QUEUE_LOCATION:-${REGION}}"
VIDSLOOM_PLANNING_WORKER_URL="${VIDSLOOM_PLANNING_WORKER_URL:-${PUBLIC_BASE_URL}/api/planning/jobs}"
VIDSLOOM_RENDER_QUEUE="${VIDSLOOM_RENDER_QUEUE:-vidsloom-render-${ENVIRONMENT}}"
VIDSLOOM_RENDER_QUEUE_LOCATION="${VIDSLOOM_RENDER_QUEUE_LOCATION:-${REGION}}"
VIDSLOOM_RENDER_WORKER_URL="${VIDSLOOM_RENDER_WORKER_URL:-${PUBLIC_BASE_URL}/api/render/jobs}"
VIDSLOOM_MEDIA_QUEUE="${VIDSLOOM_MEDIA_QUEUE:-vidsloom-media-${ENVIRONMENT}}"
VIDSLOOM_MEDIA_QUEUE_LOCATION="${VIDSLOOM_MEDIA_QUEUE_LOCATION:-${REGION}}"
VIDSLOOM_MEDIA_WORKER_URL="${VIDSLOOM_MEDIA_WORKER_URL:-${PUBLIC_BASE_URL}/api/media/jobs}"
if [[ "${ENVIRONMENT}" == "production" ]]; then
  DEFAULT_MEDIA_GENERATION_ENABLED="true"
  DEFAULT_REFERENCE_FRAME_GENERATION_ENABLED="true"
  DEFAULT_VIDEO_CLIP_GENERATION_ENABLED="true"
  DEFAULT_TTS_ENABLED="true"
  DEFAULT_PREMIUM_VIDEO_MAX_CLIPS="1"
  DEFAULT_MEDIA_BUDGET_PER_CAMPAIGN_CENTS="2000"
else
  DEFAULT_MEDIA_GENERATION_ENABLED="false"
  DEFAULT_REFERENCE_FRAME_GENERATION_ENABLED="false"
  DEFAULT_VIDEO_CLIP_GENERATION_ENABLED="false"
  DEFAULT_TTS_ENABLED="false"
  DEFAULT_PREMIUM_VIDEO_MAX_CLIPS="1"
  DEFAULT_MEDIA_BUDGET_PER_CAMPAIGN_CENTS="0"
fi
VIDSLOOM_MEDIA_GENERATION_ENABLED="${VIDSLOOM_MEDIA_GENERATION_ENABLED:-${DEFAULT_MEDIA_GENERATION_ENABLED}}"
VIDSLOOM_REFERENCE_FRAME_GENERATION_ENABLED="${VIDSLOOM_REFERENCE_FRAME_GENERATION_ENABLED:-${DEFAULT_REFERENCE_FRAME_GENERATION_ENABLED}}"
VIDSLOOM_VIDEO_CLIP_GENERATION_ENABLED="${VIDSLOOM_VIDEO_CLIP_GENERATION_ENABLED:-${DEFAULT_VIDEO_CLIP_GENERATION_ENABLED}}"
VIDSLOOM_TTS_ENABLED="${VIDSLOOM_TTS_ENABLED:-${DEFAULT_TTS_ENABLED}}"
VIDSLOOM_PREMIUM_VIDEO_MAX_CLIPS="${VIDSLOOM_PREMIUM_VIDEO_MAX_CLIPS:-${DEFAULT_PREMIUM_VIDEO_MAX_CLIPS}}"
VIDSLOOM_MEDIA_BUDGET_PER_CAMPAIGN_CENTS="${VIDSLOOM_MEDIA_BUDGET_PER_CAMPAIGN_CENTS:-${DEFAULT_MEDIA_BUDGET_PER_CAMPAIGN_CENTS}}"
VIDSLOOM_ALLOW_UNBUDGETED_MEDIA_GENERATION="${VIDSLOOM_ALLOW_UNBUDGETED_MEDIA_GENERATION:-false}"
VIDSLOOM_MEDIA_TASK_DISPATCH_DEADLINE_SECONDS="${VIDSLOOM_MEDIA_TASK_DISPATCH_DEADLINE_SECONDS:-1800}"
VIDSLOOM_PUBLISHING_QUEUE="${VIDSLOOM_PUBLISHING_QUEUE:-vidsloom-publishing-${ENVIRONMENT}}"
VIDSLOOM_PUBLISHING_QUEUE_LOCATION="${VIDSLOOM_PUBLISHING_QUEUE_LOCATION:-${REGION}}"
VIDSLOOM_PUBLISHING_WORKER_URL="${VIDSLOOM_PUBLISHING_WORKER_URL:-${PUBLIC_BASE_URL}/api/publishing/jobs}"
STRIPE_SECRET_KEY_SECRET_NAME="${STRIPE_SECRET_KEY_SECRET_NAME:-}"
STRIPE_WEBHOOK_SECRET_NAME="${STRIPE_WEBHOOK_SECRET_NAME:-}"
STRIPE_PRICE_STARTER_SECRET_NAME="${STRIPE_PRICE_STARTER_SECRET_NAME:-}"
STRIPE_PRICE_GROWTH_SECRET_NAME="${STRIPE_PRICE_GROWTH_SECRET_NAME:-}"
VIDSLOOM_TOKEN_ENCRYPTION_SECRET_NAME="${VIDSLOOM_TOKEN_ENCRYPTION_SECRET_NAME:-}"
VIDSLOOM_YOUTUBE_CLIENT_ID="${VIDSLOOM_YOUTUBE_CLIENT_ID:-696791188703-gj1l112emiohd3l41t13mn15bqhcebhi.apps.googleusercontent.com}"
VIDSLOOM_YOUTUBE_CLIENT_SECRET_NAME="${VIDSLOOM_YOUTUBE_CLIENT_SECRET_NAME:-vidsloom_youtube_client_secret}"
VIDSLOOM_TIKTOK_CLIENT_SECRET_NAME="${VIDSLOOM_TIKTOK_CLIENT_SECRET_NAME:-}"
VIDSLOOM_META_APP_SECRET_NAME="${VIDSLOOM_META_APP_SECRET_NAME:-}"
VIDSLOOM_LINKEDIN_CLIENT_SECRET_NAME="${VIDSLOOM_LINKEDIN_CLIENT_SECRET_NAME:-}"
GEMINI_MODEL="${GEMINI_MODEL:-gemini-2.5-flash}"
GEMINI_FALLBACK_MODEL="${GEMINI_FALLBACK_MODEL:-gemini-2.5-flash-lite}"
GEMINI_IMAGE_MODEL="${GEMINI_IMAGE_MODEL:-gemini-2.5-flash-image}"
GEMINI_VIDEO_MODEL="${GEMINI_VIDEO_MODEL:-veo-3.1-generate-001}"
GEMINI_TTS_MODEL="${GEMINI_TTS_MODEL:-gemini-3.1-flash-tts-preview}"
VIDSLOOM_GEMINI_RETRY_ATTEMPTS="${VIDSLOOM_GEMINI_RETRY_ATTEMPTS:-4}"
VIDSLOOM_GEMINI_RETRY_BASE_MS="${VIDSLOOM_GEMINI_RETRY_BASE_MS:-5000}"
VIDSLOOM_GEMINI_RETRY_MAX_MS="${VIDSLOOM_GEMINI_RETRY_MAX_MS:-45000}"
ENV_VAR_DELIMITER="~"
STRIPE_REQUIRE_TEST_MODE="false"
STRIPE_REQUIRE_LIVE_MODE="false"
if [[ "${ENVIRONMENT}" == "staging" ]]; then
  STRIPE_REQUIRE_TEST_MODE="true"
else
  STRIPE_REQUIRE_LIVE_MODE="true"
fi
ENV_VARS="^${ENV_VAR_DELIMITER}^VIDSLOOM_ENV=${ENVIRONMENT}${ENV_VAR_DELIMITER}VIDSLOOM_PUBLIC_BASE_URL=${PUBLIC_BASE_URL}${ENV_VAR_DELIMITER}VIDSLOOM_STORAGE=firestore${ENV_VAR_DELIMITER}VIDSLOOM_RENDER_DYNAMIC_ASSETS=true${ENV_VAR_DELIMITER}VIDSLOOM_RENDER_MAX_ASSETS=5${ENV_VAR_DELIMITER}VIDSLOOM_RENDER_CONCURRENCY=2${ENV_VAR_DELIMITER}VIDSLOOM_PLANNING_QUEUE=${VIDSLOOM_PLANNING_QUEUE}${ENV_VAR_DELIMITER}VIDSLOOM_PLANNING_QUEUE_LOCATION=${VIDSLOOM_PLANNING_QUEUE_LOCATION}${ENV_VAR_DELIMITER}VIDSLOOM_RENDER_QUEUE=${VIDSLOOM_RENDER_QUEUE}${ENV_VAR_DELIMITER}VIDSLOOM_RENDER_QUEUE_LOCATION=${VIDSLOOM_RENDER_QUEUE_LOCATION}${ENV_VAR_DELIMITER}VIDSLOOM_MEDIA_QUEUE=${VIDSLOOM_MEDIA_QUEUE}${ENV_VAR_DELIMITER}VIDSLOOM_MEDIA_QUEUE_LOCATION=${VIDSLOOM_MEDIA_QUEUE_LOCATION}${ENV_VAR_DELIMITER}VIDSLOOM_MEDIA_WORKER_URL=${VIDSLOOM_MEDIA_WORKER_URL}${ENV_VAR_DELIMITER}VIDSLOOM_MEDIA_GENERATION_ENABLED=${VIDSLOOM_MEDIA_GENERATION_ENABLED}${ENV_VAR_DELIMITER}VIDSLOOM_REFERENCE_FRAME_GENERATION_ENABLED=${VIDSLOOM_REFERENCE_FRAME_GENERATION_ENABLED}${ENV_VAR_DELIMITER}VIDSLOOM_VIDEO_CLIP_GENERATION_ENABLED=${VIDSLOOM_VIDEO_CLIP_GENERATION_ENABLED}${ENV_VAR_DELIMITER}VIDSLOOM_TTS_ENABLED=${VIDSLOOM_TTS_ENABLED}${ENV_VAR_DELIMITER}VIDSLOOM_PREMIUM_VIDEO_MAX_CLIPS=${VIDSLOOM_PREMIUM_VIDEO_MAX_CLIPS}${ENV_VAR_DELIMITER}VIDSLOOM_MEDIA_BUDGET_PER_CAMPAIGN_CENTS=${VIDSLOOM_MEDIA_BUDGET_PER_CAMPAIGN_CENTS}${ENV_VAR_DELIMITER}VIDSLOOM_ALLOW_UNBUDGETED_MEDIA_GENERATION=${VIDSLOOM_ALLOW_UNBUDGETED_MEDIA_GENERATION}${ENV_VAR_DELIMITER}VIDSLOOM_PUBLISHING_QUEUE=${VIDSLOOM_PUBLISHING_QUEUE}${ENV_VAR_DELIMITER}VIDSLOOM_PUBLISHING_QUEUE_LOCATION=${VIDSLOOM_PUBLISHING_QUEUE_LOCATION}${ENV_VAR_DELIMITER}GOOGLE_GENAI_USE_ENTERPRISE=true${ENV_VAR_DELIMITER}GOOGLE_CLOUD_PROJECT=${PROJECT_ID}${ENV_VAR_DELIMITER}GOOGLE_CLOUD_LOCATION=us-central1${ENV_VAR_DELIMITER}GEMINI_MODEL=${GEMINI_MODEL}${ENV_VAR_DELIMITER}GEMINI_FALLBACK_MODEL=${GEMINI_FALLBACK_MODEL}${ENV_VAR_DELIMITER}GEMINI_IMAGE_MODEL=${GEMINI_IMAGE_MODEL}${ENV_VAR_DELIMITER}GEMINI_VIDEO_MODEL=${GEMINI_VIDEO_MODEL}${ENV_VAR_DELIMITER}GEMINI_TTS_MODEL=${GEMINI_TTS_MODEL}${ENV_VAR_DELIMITER}VIDSLOOM_GEMINI_RETRY_ATTEMPTS=${VIDSLOOM_GEMINI_RETRY_ATTEMPTS}${ENV_VAR_DELIMITER}VIDSLOOM_GEMINI_RETRY_BASE_MS=${VIDSLOOM_GEMINI_RETRY_BASE_MS}${ENV_VAR_DELIMITER}VIDSLOOM_GEMINI_RETRY_MAX_MS=${VIDSLOOM_GEMINI_RETRY_MAX_MS}${ENV_VAR_DELIMITER}NODE_ENV=production${ENV_VAR_DELIMITER}STRIPE_REQUIRE_TEST_MODE=${STRIPE_REQUIRE_TEST_MODE}${ENV_VAR_DELIMITER}STRIPE_REQUIRE_LIVE_MODE=${STRIPE_REQUIRE_LIVE_MODE}"
SECRET_ARGS=()

if [[ "${ENVIRONMENT}" != "staging" && "${ENVIRONMENT}" != "production" ]]; then
  echo "Usage: scripts/deploy-cloud-run.sh [staging|production]" >&2
  exit 1
fi

if [[ "${SKIP_DEPLOY_PREFLIGHT}" != "true" ]]; then
  echo "Running deploy preflight: typecheck, lint, build, video visual QA, and page visual QA."
  npm run typecheck
  npm run lint
  npm run build
  npm run visual:videos
  GOOGLE_GENAI_USE_ENTERPRISE="${GOOGLE_GENAI_USE_ENTERPRISE:-true}" GOOGLE_CLOUD_PROJECT="${PROJECT_ID}" GOOGLE_CLOUD_LOCATION="${GOOGLE_CLOUD_LOCATION:-us-central1}" npm run visual:videos:ai
  npm run visual:pages
  GOOGLE_GENAI_USE_ENTERPRISE="${GOOGLE_GENAI_USE_ENTERPRISE:-true}" GOOGLE_CLOUD_PROJECT="${PROJECT_ID}" GOOGLE_CLOUD_LOCATION="${GOOGLE_CLOUD_LOCATION:-us-central1}" npm run visual:pages:ai
elif [[ "${ENVIRONMENT}" == "production" && "${SKIP_VIDEO_QA:-false}" != "true" ]]; then
  echo "Running mandatory production visual QA gates."
  npm run visual:videos
  GOOGLE_GENAI_USE_ENTERPRISE="${GOOGLE_GENAI_USE_ENTERPRISE:-true}" GOOGLE_CLOUD_PROJECT="${PROJECT_ID}" GOOGLE_CLOUD_LOCATION="${GOOGLE_CLOUD_LOCATION:-us-central1}" npm run visual:videos:ai
  npm run visual:pages
  GOOGLE_GENAI_USE_ENTERPRISE="${GOOGLE_GENAI_USE_ENTERPRISE:-true}" GOOGLE_CLOUD_PROJECT="${PROJECT_ID}" GOOGLE_CLOUD_LOCATION="${GOOGLE_CLOUD_LOCATION:-us-central1}" npm run visual:pages:ai
fi

if [[ -z "${STRIPE_SECRET_KEY_SECRET_NAME}" ]]; then
  if [[ "${ENVIRONMENT}" == "production" ]]; then
    STRIPE_SECRET_KEY_SECRET_NAME="STRIPE_SECRET_KEY_PRODUCTION"
  else
    STRIPE_SECRET_KEY_SECRET_NAME="STRIPE_SECRET_KEY_STAGING"
  fi
fi

if [[ -z "${STRIPE_WEBHOOK_SECRET_NAME}" ]]; then
  if [[ "${ENVIRONMENT}" == "production" ]]; then
    STRIPE_WEBHOOK_SECRET_NAME="STRIPE_WEBHOOK_SECRET_PRODUCTION"
  else
    STRIPE_WEBHOOK_SECRET_NAME="STRIPE_WEBHOOK_SECRET_STAGING"
  fi
fi

if [[ -z "${STRIPE_PRICE_STARTER_SECRET_NAME}" ]]; then
  if [[ "${ENVIRONMENT}" == "production" ]]; then
    STRIPE_PRICE_STARTER_SECRET_NAME="STRIPE_PLATFORM_PRICE_STARTER_PRODUCTION"
  else
    STRIPE_PRICE_STARTER_SECRET_NAME="STRIPE_PLATFORM_PRICE_STARTER_STAGING"
  fi
fi

if [[ -z "${STRIPE_PRICE_GROWTH_SECRET_NAME}" ]]; then
  if [[ "${ENVIRONMENT}" == "production" ]]; then
    STRIPE_PRICE_GROWTH_SECRET_NAME="STRIPE_PLATFORM_PRICE_PRO_PRODUCTION"
  else
    STRIPE_PRICE_GROWTH_SECRET_NAME="STRIPE_PLATFORM_PRICE_PRO_STAGING"
  fi
fi

append_env_var() {
  local key="$1"
  local value="${!key:-}"
  if [[ -n "${value}" ]]; then
    ENV_VARS="${ENV_VARS}${ENV_VAR_DELIMITER}${key}=${value}"
  fi
}

append_env_var "SENDGRID_FROM_EMAIL"
append_env_var "SENDGRID_FROM_NAME"
append_env_var "SENDGRID_REPLY_TO_EMAIL"
append_env_var "VIDSLOOM_SALES_EMAIL"
append_env_var "SENDGRID_NOTIFY_EMAIL"
append_env_var "SENDGRID_LEAD_AUTORESPONDER_TEMPLATE_ID"
append_env_var "SENDGRID_OWNER_LEAD_TEMPLATE_ID"
append_env_var "SENDGRID_MARKETING_LIST_IDS"
append_env_var "SENDGRID_CONTACTDB_LIST_IDS"
append_env_var "SENDGRID_LEGACY_CONTACTDB_LIST_IDS"
append_env_var "VIDSLOOM_WHATSAPP_NUMBER"
append_env_var "VIDSLOOM_SMS_NUMBER"
append_env_var "VIDSLOOM_QA_USERNAME"
append_env_var "VIDSLOOM_GENERATED_ASSET_BUCKET"
append_env_var "VIDSLOOM_ASSET_BUCKET"
append_env_var "VIDSLOOM_RENDER_DYNAMIC_ASSETS"
append_env_var "VIDSLOOM_RENDER_MAX_ASSETS"
append_env_var "VIDSLOOM_RENDER_CONCURRENCY"
append_env_var "VIDSLOOM_PLANNING_WORKER_URL"
append_env_var "VIDSLOOM_RENDER_WORKER_URL"
append_env_var "VIDSLOOM_MEDIA_WORKER_URL"
append_env_var "VIDSLOOM_MEDIA_GENERATION_ENABLED"
append_env_var "VIDSLOOM_REFERENCE_FRAME_GENERATION_ENABLED"
append_env_var "VIDSLOOM_VIDEO_CLIP_GENERATION_ENABLED"
append_env_var "VIDSLOOM_TTS_ENABLED"
append_env_var "VIDSLOOM_PREMIUM_VIDEO_MAX_CLIPS"
append_env_var "VIDSLOOM_MEDIA_BUDGET_PER_CAMPAIGN_CENTS"
append_env_var "VIDSLOOM_MEDIA_TASK_DISPATCH_DEADLINE_SECONDS"
append_env_var "VIDSLOOM_PUBLISHING_WORKER_URL"
append_env_var "VIDSLOOM_YOUTUBE_CLIENT_ID"
append_env_var "VIDSLOOM_YOUTUBE_PRIVACY_STATUS"
append_env_var "VIDSLOOM_TIKTOK_CLIENT_KEY"
append_env_var "VIDSLOOM_TIKTOK_DEFAULT_PRIVACY"
append_env_var "VIDSLOOM_META_APP_ID"
append_env_var "VIDSLOOM_META_GRAPH_VERSION"
append_env_var "VIDSLOOM_LINKEDIN_CLIENT_ID"
append_env_var "VIDSLOOM_LINKEDIN_VERSION"

if [[ -n "${SENDGRID_SECRET_NAME:-}" ]]; then
  SECRET_ARGS+=(--set-secrets="SENDGRID_API_KEY=${SENDGRID_SECRET_NAME}:latest")
fi

if [[ -n "${VIDSLOOM_QA_PASSWORD_SECRET_NAME:-}" ]]; then
  SECRET_ARGS+=(--set-secrets="VIDSLOOM_QA_PASSWORD=${VIDSLOOM_QA_PASSWORD_SECRET_NAME}:latest")
fi

if [[ -n "${VIDSLOOM_AUTH_SECRET_NAME:-}" ]]; then
  SECRET_ARGS+=(--set-secrets="VIDSLOOM_AUTH_SECRET=${VIDSLOOM_AUTH_SECRET_NAME}:latest")
fi

if [[ -n "${VIDSLOOM_AUTOMATION_SECRET_NAME:-}" ]]; then
  SECRET_ARGS+=(--set-secrets="VIDSLOOM_AUTOMATION_SECRET=${VIDSLOOM_AUTOMATION_SECRET_NAME}:latest")
fi

if [[ -n "${VIDSLOOM_TOKEN_ENCRYPTION_SECRET_NAME:-}" ]]; then
  SECRET_ARGS+=(--set-secrets="VIDSLOOM_TOKEN_ENCRYPTION_SECRET=${VIDSLOOM_TOKEN_ENCRYPTION_SECRET_NAME}:latest")
fi

if [[ -n "${VIDSLOOM_YOUTUBE_CLIENT_SECRET_NAME:-}" ]]; then
  SECRET_ARGS+=(--set-secrets="VIDSLOOM_YOUTUBE_CLIENT_SECRET=${VIDSLOOM_YOUTUBE_CLIENT_SECRET_NAME}:latest")
fi

if [[ -n "${VIDSLOOM_TIKTOK_CLIENT_SECRET_NAME:-}" ]]; then
  SECRET_ARGS+=(--set-secrets="VIDSLOOM_TIKTOK_CLIENT_SECRET=${VIDSLOOM_TIKTOK_CLIENT_SECRET_NAME}:latest")
fi

if [[ -n "${VIDSLOOM_META_APP_SECRET_NAME:-}" ]]; then
  SECRET_ARGS+=(--set-secrets="VIDSLOOM_META_APP_SECRET=${VIDSLOOM_META_APP_SECRET_NAME}:latest")
fi

if [[ -n "${VIDSLOOM_LINKEDIN_CLIENT_SECRET_NAME:-}" ]]; then
  SECRET_ARGS+=(--set-secrets="VIDSLOOM_LINKEDIN_CLIENT_SECRET=${VIDSLOOM_LINKEDIN_CLIENT_SECRET_NAME}:latest")
fi

if [[ -n "${STRIPE_SECRET_KEY_SECRET_NAME:-}" ]]; then
  SECRET_ARGS+=(--set-secrets="STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY_SECRET_NAME}:latest")
fi

if [[ -n "${STRIPE_WEBHOOK_SECRET_NAME:-}" ]]; then
  SECRET_ARGS+=(--set-secrets="STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET_NAME}:latest")
fi

if [[ -n "${STRIPE_PRICE_STARTER_SECRET_NAME:-}" ]]; then
  SECRET_ARGS+=(--set-secrets="STRIPE_PRICE_STARTER=${STRIPE_PRICE_STARTER_SECRET_NAME}:latest")
fi

if [[ -n "${STRIPE_PRICE_GROWTH_SECRET_NAME:-}" ]]; then
  SECRET_ARGS+=(--set-secrets="STRIPE_PRICE_GROWTH=${STRIPE_PRICE_GROWTH_SECRET_NAME}:latest")
fi

gcloud run deploy "${SERVICE}" \
  --project="${PROJECT_ID}" \
  --region="${REGION}" \
  --source="." \
  --service-account="${SERVICE_ACCOUNT}" \
  --allow-unauthenticated \
  --set-env-vars="${ENV_VARS}" \
  "${SECRET_ARGS[@]}" \
  --memory=2Gi \
  --cpu=2 \
  --timeout="${CLOUD_RUN_TIMEOUT_SECONDS}" \
  --min-instances=0 \
  --max-instances=5
